In [1]:
import torch
import numpy as np

In [2]:
x = torch.rand(2,3)

In [3]:
print(x)

tensor([[0.0943, 0.2507, 0.4569],
        [0.0048, 0.4713, 0.2544]])


In [4]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data) #tensor로 변환

In [5]:
#numpy array to tensor
np_array = np.array(data)
print(np_array)
print(torch.tensor(np_array))

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [6]:
#ones_like : 동일한 크기(shape) 지만 1으로 값이 채워진 텐서를 생성(retains the properties)
x_ones = torch.ones_like(x_data)
print(x_ones) #x_data와 shape이 동일한 tensor 생성

x_rand = torch.rand_like(x_data, dtype=torch.float) #overrides the datatype of x_data
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.9542, 0.9209],
        [0.1721, 0.9195]])


In [7]:
# shape = (# of rows, # of columns)
shape = (2,3) #tuple
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.0874, 0.8687, 0.9242],
        [0.4128, 0.5652, 0.2994]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [8]:
#attributes of a tensor
tensor = torch.rand(3,4)

print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


In [9]:
# tensor 연산은 기본적으로 cpu에서 실행되지만, gpu에서 하는 것이 훨씬 빠르므로, 가능한지 check 후 전환
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

### Indexing and Slicing in Tensor

In [10]:
tensor = torch.ones(4,4)
print('first row: ', tensor[0])
print('first column', tensor[:, 0])
print('last column', tensor[..., -1])
tensor[:,1] = 0 #1번째 column 값을 바꿈
print(tensor)

first row:  tensor([1., 1., 1., 1.])
first column tensor([1., 1., 1., 1.])
last column tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [12]:
#Joining tensors
# torch.cat vs torch.stack
t = torch.cat([tensor,tensor, tensor], dim=1)
print(t)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [20]:
# Arithmetic operations
# 행렬곱 연산(matrix multiplication)을 나타내는 다양한 표현
t1 = tensor @ tensor.T
t2 = tensor.matmul(tensor.T)
t3 = torch.rand_like(tensor)
print(t1)
print(t2)
print(t3)
torch.matmul(tensor, tensor.T, out=t3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[0.7060, 0.6343, 0.6747, 0.4376],
        [0.3205, 0.4097, 0.3150, 0.5032],
        [0.9475, 0.9207, 0.8410, 0.6549],
        [0.2627, 0.0353, 0.0378, 0.3664]])


tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [22]:
# element wise product (각 행렬의 원소 끼리의 곱)
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [27]:
# tensor 을 single element value로 요약 통계량 나타내기
agg = tensor.sum() 
print(tensor)
print(agg)
agg_item = agg.item() #단일 float로 뽑아내기 위해서는 item 함수 사용
print(agg_item, type(agg_item))

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor(12.)
12.0 <class 'float'>


In [31]:
# 피 연산자(operand)에 값을 추가하는 것을 in-place 연산이라고 하며 '_'을 사용하여 수행
print(tensor)
tensor.add_(5)
print(tensor)

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])
tensor([[16., 15., 16., 16.],
        [16., 15., 16., 16.],
        [16., 15., 16., 16.],
        [16., 15., 16., 16.]])


In [35]:
# change tensor to numpy array
t = torch.ones(5)
print(f"t : {t}")

n  =t.numpy()
print(f"n : {n}")

# in-place 연산을 취하면 메모리를 공유하기에 n에도 영향을 미친다
t.add_(1)
print(f"t : {t}")
print(f"n : {n}")


t : tensor([1., 1., 1., 1., 1.])
n : [1. 1. 1. 1. 1.]
t : tensor([2., 2., 2., 2., 2.])
n : [2. 2. 2. 2. 2.]


In [17]:
data = [[2,3],[1,2]]
t_data = torch.tensor(data)

t1 = t_data @ t_data.T
print(t1)

tensor([[13,  8],
        [ 8,  5]])
